raise Exception('This is exceptional')